name: curp
description: 'A package to easily validate and parse a Mexican CURP.'
version: 1.0.0
homepage: https://github.com/pastelcode/curp
repository: https://github.com/pastelcode/curp
issue_tracker: https://github.com/pastelcode/curp/issues
topics: [curp, mexico, mexican, ine]

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
